<?php
/**
 * Created by PhpStorm.
 * User: AMojumder
 * Date: 27/06/14
 * Time: 10:51
 */
?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="/js/storelocator/jquery.bpopup.min.js"></script>

<?


//$storeCode      = $this->getRequest()->getParam('storeCode');
$uniqueName     = $this->getRequest()->getParam('name');
$res = $this->getStoreDetails($uniqueName);
//echo '<pre>'; print_r($res);
$store_details      = $res['store_details'];
//$hours      = $res['hours'];
$services   = $res['services'];
$holiday    = $res['holiday'];
$near_by    = $res['near_by'];
$branchName = $store_details['branch_name'];
?>


<head>
    <script src="http://maps.google.com/maps/api/js?sensor=false"
            type="text/javascript"></script>
</head>
<style>
    .clear{
        clear : both;
    }
    body{
        background-color: #D2E0E6;
    }
    #store_details{
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        padding-left: 0;
        background-color: #fff;
        /*height: 1800px;*/
    }
    #banner_map{
        width: 100%;
        height: 300px;
    }
    #banner{
        float: left;
        width: 67%;
        height: 100%;
        margin: 10px;
    }
    #banner img{
        width: 100%;
        height: 100%;
    }
    #map-canvas{
        float: right;
        width: 28%;
        height: 300px;
        margin: 10px;
    }

    #body_main{
        width: 100%;
        height: 1800px;
    }
    #content{
        float: left;
        width: 67%;
        height: 100%;
        padding: 10px;
        border-right: 2px solid #000000;
    }
    #aside{
        float: right;
        width: 28%;
        height: 100%;
        padding: 10px;
    }
    #aside div{
        margin: 10px 0;
    }
    #location{

    }
    #action{

    }
    #our_colleagues img{
        width: 100%;
        height:200px;
    }
    #near_by_stores{

    }

    @media only screen and (max-width:479px) {
        #content, #aside {
            width: 100%;
            height: auto;
        }
        #content {
            border: none;
            padding: 0;
        }
        #content div {
            width: 100%;
        }
        #body_main {
            height: auto;
        }
    }

</style>

<a href="/storelocator"> storeLocator </a>
<div id="store_details" >
    <div id="banner_map">
        <div id="map-canvas"> </div>
        <div id="banner">
            <img src="<?=$store_details['banner']?>"/>
        </div>
    </div>
    <div class="clear"></div>
    <div id="body_main">

        <div id="aside">
            <div id="location">
                <h2> Location </h2>
                <?=$store_details['address1']?> <br />
                <? echo ($store_details['town']) ? $store_details['town'].'<br />' : NULL ; ?>
                <? echo ($store_details['city']) ? $store_details['city'].'<br />' : NULL ; ?>
                <? echo ($store_details['county']) ? $store_details['county'].'<br />' : NULL ; ?>
                <? echo ($store_details['postcode']) ? $store_details['postcode'].'<br />' : NULL ; ?>
            </div>
            <br /><br />
            <div id="action">
                Print This Informaion <br />
                Download This Page <br />
                <? echo ($store_details['telephone1']) ? $store_details['telephone1'].'<br />' : NULL ; ?>
                Email This Store
            </div>
            <? if ($services) {?>
                <div id="services">
                    <h2> Services Available </h2>
                    <? foreach ($services as $row){
                        echo $row['service_name'].'<br />';
                    }?>
                </div> <?}?>
            <div id="our_colleagues">
                <img src="<?=$store_details['aside_img']?>"/>
            </div>
            <? if ($near_by) {?> <br />
                <div id="near_by_stores">
                <h2> Near By Stores </h2>
                <? foreach ($near_by as $row){
                    echo $row['branch_name'].' '.'<br />';
                }?>
                </div><?}?>
            <br />
                <div id="opening">
                    <h2> Opening Times </h2>
                    <?
                    if($holiday){
                        echo "<b> Bank Holiday Hours</b> <br />";
                        foreach ($holiday as $row){
                            echo date( 'l dS M', strtotime($row['holiday_date'])).' :  '.$this->numToMin($row['from_']).' '.$this->numToMin($row['to_']).' '.'<br />';
                        }// End of for each $holiday
                       echo "<br />";  } // End if empty array?>

                    <?
                        echo 'Monday  '.$this->numToMin($store_details['mon_open']).' '.$this->numToMin($store_details['mon_close']).' '.'<br />';
                        echo 'Tuesday  '.$this->numToMin($store_details['tues_open']).' '.$this->numToMin($store_details['tues_close']).' '.'<br />';
                        echo 'Wednesday  '.$this->numToMin($store_details['wednes_open']).' '.$this->numToMin($store_details['wednes_close']).' '.'<br />';
                        echo 'Thursday  '.$this->numToMin($store_details['thurs_open']).' '.$this->numToMin($store_details['thurs_close']).' '.'<br />';
                        echo 'Friday  '.$this->numToMin($store_details['fri_open']).' '.$this->numToMin($store_details['fri_close']).' '.'<br />';
                        echo 'Saturday  '.$this->numToMin($store_details['satur_open']).' '.$this->numToMin($store_details['satur_close']).' '.'<br />';
                        echo 'Sunday  '.$this->numToMin($store_details['sun_open']).' '.$this->numToMin($store_details['sun_close']).' '.'<br />';
                    ?>
                </div>
        </div>
        <div id="content">
            <div id="about_store">
                <h1> <?=$store_details['branch_title']?>  </h1>
                <?=$store_details['branch_description']?>
            </div>
            <hr>
            <div id="about_location">
                <h1> <?=$store_details['location_title']?>  </h1>
                <?=$store_details['location_description']?>
            </div>
            <hr>
            <div id="near_us">
                <h1><?=$store_details['near_us_title']?>  </h1>
                <? $a=  $store_details['near_us_description'];
                eval("\$a = \"$a\";");
                echo $a;?>
            </div>
        </div>

    </div>
    <div class="clear"></div>
    <!--    window.scrollTo(x-coord, y-coord);-->
</div>

<script>
//    $('#map-canvas').hover(
//        function(){
//            $('#banner').hide();
//        },
//        function(){
//            $('#banner').show();
//        }
//    );
</script>

<script>
    var map;
    var image = 'http://www.bluemarketingfirm.com/images/mapmarker_shadow.png';
    var shadow = new google.maps.MarkerImage('http://www.snazzy-apps.com/navstarUS/img/icon_marker.png',
        new google.maps.Size(51, 37),
        new google.maps.Point(0,0),
        new google.maps.Point(0, 37));

    function initialize() {
        var latlng = new google.maps.LatLng(<?=$store_details['lat']?>, <?=$store_details['lng']?>);
        var options = {
            zoom: <?=$store_details['map_zoom_branch_page']?>,
            center: latlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl: true,
            mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR,
                position: google.maps.ControlPosition.TOP_CENTER
            },
            panControl: true,
            panControlOptions: {
                position: google.maps.ControlPosition.RIGHT_TOP
            },
            zoomControl: true,
            zoomControlOptions: {
                style: google.maps.ZoomControlStyle.DEFAULT,
                position: google.maps.ControlPosition.RIGHT_CENTER
            },
            scaleControl: true,  // fixed to BOTTOM_RIGHT
            streetViewControl: true,
            streetViewControlOptions: {
                position: google.maps.ControlPosition.RIGHT_CENTER
            }
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"), options);

        var marker = new google.maps.Marker({
            position: latlng,
            map: map,
            icon: image,
            shadow: shadow,
            title:"<?=$store_details['branch_name']?>"
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>