<?
//https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=sql+search+within+10+mile+radius+longlat&spell=1
//http://stackoverflow.com/questions/8994718/mysql-longitude-and-latitude-query-for-other-rows-within-x-mile-radius
//http://gis.stackexchange.com/questions/31628/find-points-within-a-distance-using-mysql
//http://stackoverflow.com/questions/7075912/how-to-convert-postcode-to-geolocationlatitude-longitutde-using-google-maps
?>
<html>
<head>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBl-XFi-PrFDZgDYRRD3PDtY4-xcRt6lkA&sensor=false"> </script>
</head>
<body>
<?
//$one = "<script>document.getElementById('lng').value </script>";
//echo $one; exit;
$address  = $this->getRequest()->getPost('address');
if (empty($address)){
    $initZoom       = 6;
    $centerLat      = 53.089362; // "<script>document.getElementById('lat').value</script>";//
    $centerLng      = -4.852386; // "<script>document.getElementById('lng').value</script>"; //
    $res            = $this->getAllStores();
}else{
    $initZoom       = 9;
    $center         = $this->getCenter($address);
    $centerLat      = floatval($center['lat']); // 51.677; //
    $centerLng      = floatval($center['lng']); //-0.606; //
    $res            = $this->getStoresLatLng($centerLat,$centerLng);
}
?>
<style>
    #searchArea{
        height:50px;
    }
    #searchArea p{
        float: left;
        font-size: 20px;
    }
    #searchArea form{
        height:50px;
        float: right;
    }
    .searchBox{
        height:31px;
        width: 200px;
        -moz-border-radius:7px;
        -webkit-border-radius:7px;
        border-radius:7px;
        border:1px solid #000;
        padding:2px 27px;
    }
    .searchButton {
        background-color:#000;
        -moz-border-radius:7px;
        -webkit-border-radius:7px;
        border-radius:7px;
        border:1px solid #000;
        display:inline-block;
        cursor:pointer;
        color:#ffffff;
        font-family:arial;
        font-size:17px;
        padding:10px 27px;
        text-decoration:none;
        text-shadow:0px 1px 0px #000;
    }
    .searchButton:hover {
        background-color:#5cbf2a;
    }
    .searchButton:active {
        position:relative;
        top:1px;
    }

    .description{
        margin: 20px 5px;
    }
    .storesList{
        border-bottom: 1px dotted #0000ff;
        width: 100%;
        padding: 15px 5px 2px 5px;
    }
    .viewOnMap{
        float: right;
        margin: -30px 75px 0 0;
        font-weight:bold;
        text-decoration: none;
    }
    .goToStore{
        float: right;
        margin-top: -30px;
        text-decoration: none;
    }
</style>

<div id='content'>
    <div id="searchArea">
        <p> Find your nearest store </p>
        <form name="input" action="<?php echo Mage::getUrl('storelocator/index/index') ?>" method='post'>
            <input type="checkbox" name="dhl" value="Bike">&nbsp;DHL &nbsp;
            <input type="checkbox" name="copy" value="Bike">&nbsp;Copy&nbsp;
            <input type="checkbox" name="scan" value="Bike">&nbsp;Scan&nbsp;
            <input type="checkbox" name="dhl2" value="Bike">&nbsp;DHL&nbsp;
            <input type="text" name="address" class="searchBox"  placeholder="Enter Town Or Postcode">
            <input type="submit" class="searchButton" value="SEARCH">
        </form>
    </div>
    <div id="googleMap" style="width:100%;height:400px;"></div>
    <input type="hidden" id="lat" value="">
    <input type="hidden" id="lng" value="">
    <input type="hidden" id="acc" value="">
    <div class="description">
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
        <p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. </p>
    </div>

    <?if(empty($res)){
        echo '<h1> Could not locate any store for GU21 5ED </h1>';
    }else {
        foreach ( $res as $row){
            $name = $row['unique_name'];
            $id = $row['id'];
            ?>
            <div class="storesList">
                <h3> <?=$row['branch_name']?> </h3>
                <p> <?=$row['address1'] . ', ' . $row['address2'] . ', '.$row['town'] . ', ' .$row['city'] . ', '  .$row['postcode']   ?>   </p>  <div class="viewOnMap"  > <a href="#" onclick="showMarker(<?=$name?>)" > View on map </a></div>
                <div class="goToStore"  > <a href="/<?=$name?>">  Go to Store </a></div>
            </div>
        <?}}?>

</div>
</body>
</html>


<script>

//    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
//        navigator.geolocation.getCurrentPosition(GetLocation);
//        function GetLocation(location) {
//            document.getElementById("lat").value = location.coords.latitude;
//            document.getElementById("lng").value = location.coords.longitude;
//            document.getElementById("acc").value = location.coords.accuracy ;
//            console.log(document.getElementById('lat').value + ' ' + document.getElementById('lng').value);
//        }
//    }else{
        document.getElementById("lat").value = <?=$centerLat?>;
        document.getElementById("lng").value = <?=$centerLng?>;
//    }

    console.log(document.getElementById('lat').value + ' ' + document.getElementById('lng').value);

    <?
       foreach ( $res as $row){ $name = $row['unique_name'] ?>

    var image = '<?=$row['map_marker_list_page']?>' ; // 'http://www.bluemarketingfirm.com/images/mapmarker_shadow.png';
    var <?=$name?> = new google.maps.LatLng(<?=$row['lat']?>, <?=$row['lng']?>);
    var <?=$name?> = new google.maps.Marker({
        position:<?=$name?>,
        icon: image,
        title:"<?=$row['branch_name']?>"
    });
    <?}?>
    function initialize()
    {
        var mapCenter = new google.maps.LatLng(document.getElementById("lat").value, document.getElementById("lng").value  );
        var infowindow = null;

        var mapProp = {
            center:mapCenter,
            zoom:<?=$initZoom?>,
            mapTypeId:google.maps.MapTypeId.ROADMAP
        };

        var map=new google.maps.Map(document.getElementById("googleMap") ,mapProp);

        <?
         foreach ( $res as $row){
            $name = $row['unique_name'];
            $map_branch_img_list_page       = $row['map_branch_img_list_page'];
            $map_zoom_list_page             = $row['map_zoom_list_page'];
            $address                        = $row['address1'].', '.$row['city'];
            $url                            = '/'.$name;
            $storeGoUrl                     = '<a href="'.$url.'"> '.$address.' </a>'; ?>

        google.maps.event.addListener( <?=$name?>,'click',function() {
            map.setZoom(<?=$map_zoom_list_page?>);
            map.setCenter(<?=$name?>.getPosition());
            if (infowindow) {
                infowindow.close();
            }
            infowindow = new google.maps.InfoWindow();
            infowindow.setContent('<img src="<?=$map_branch_img_list_page?>" width="300px"/> <br /> Visit ' + '<?=$storeGoUrl?>');
            infowindow.open(map,<?=$name?>);
        });
        <?=$name?>.setMap(map);
        <?}?>
    }

    function showMarker(marker){
        var gMarker = marker;
        var center = marker;

        google.maps.event.trigger(gMarker, 'click', {
            latLng: center
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);


</script>
