<?
//https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=sql+search+within+10+mile+radius+longlat&spell=1
//http://stackoverflow.com/questions/8994718/mysql-longitude-and-latitude-query-for-other-rows-within-x-mile-radius
//http://gis.stackexchange.com/questions/31628/find-points-within-a-distance-using-mysql
//http://stackoverflow.com/questions/7075912/how-to-convert-postcode-to-geolocationlatitude-longitutde-using-google-maps
?>

<head>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBl-XFi-PrFDZgDYRRD3PDtY4-xcRt6lkA&sensor=false"> </script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>


<style>
    #searchArea{
        height:50px;
    }
    #searchArea p{
        float: left;
        font-size: 20px;
    }
    #searchArea form{
        height:50px;
        float: right;
    }
    #searchBox{
        height:31px;
        width: 200px;
        -moz-border-radius:7px;
        -webkit-border-radius:7px;
        border-radius:7px;
        border:1px solid #000;
        padding:2px 27px;
    }
    #searchButton {
        background-color:#000;
        -moz-border-radius:7px;
        -webkit-border-radius:7px;
        border-radius:7px;
        border:1px solid #000;
        display:inline-block;
        cursor:pointer;
        color:#ffffff;
        font-family:arial;
        font-size:17px;
        padding:10px 27px;
        text-decoration:none;
        text-shadow:0px 1px 0px #000;
    }
    #searchButton:hover {
        background-color:#5cbf2a;
    }
    #searchButton:active {
        position:relative;
        top:1px;
    }

    .description{
        margin: 20px 5px;
    }
    #storesList{
        display: none;
        width: 100%;
    }
    #markers{
        display: none;
        width: 100%;
    }
    .store{
        border-bottom: 1px dotted #0000ff;
        width: 100%;
        padding: 15px 5px 2px 5px;
    }
    .viewOnMap{
        float: right;
        margin: -30px 75px 0 0;
        font-weight:bold;
        text-decoration: none;
    }
    .goToStore{
        float: right;
        margin-top: -30px;
        text-decoration: none;
    }
    .infoWindow{
        width: 400px;
        height: 200px;
        background-color: #ffffff;
        margin: 20px 10px 10px 10px;
    }
    .openingHours{
        width: 200px;
        float: right;
        height: 200px;
    }
    .openingHoursTitle{
        font-size: 16px;
        font-weight: bold;

    }
    .details{
        width: 200px;
        float: left;
        text-align: left;
        height: 200px;
    }
    #nxt{
        float: right;
    }
    #prv{
        float: left;
    }
    #nxtPrv{
        width:100%;
        padding: 0 0 30px 0;
    }
    #lookingCoordinates‎{
        display: none;
    }

</style>


<? include_once('indexMobile.phtml') ?>


