<body>


<??>

<div id='content'>
    <div id="lookingCoordinates‎" style="display:none;width:300px; border:1px solid black;position:absolute;
        top:40%;left:40%;padding:2px; background:#fff; text-align: center; z-index: 1;">
        <img src='http://www.hocsinc.com/images/please-wait-ani.gif' width="300"/> <br />
    </div>

    <div id="searchArea">
        <p> Find your nearest store </p>
        <form name="input" action="<?php echo Mage::getUrl('storelocator/index/index') ?>" method='post'>
<!--            <input type="checkbox" name="dhl" value="Bike">&nbsp;DHL &nbsp;-->
<!--            <input type="checkbox" name="copy" value="Bike">&nbsp;Copy&nbsp;-->
<!--            <input type="checkbox" name="scan" value="Bike">&nbsp;Scan&nbsp;-->
<!--            <input type="checkbox" name="dhl2" value="Bike">&nbsp;DHL&nbsp;-->
            <input type="text" name="address" id="searchBox" value="" placeholder="Enter Town Or Postcode">
            <input type="submit" id="searchButton" value="SEARCH">
        </form>
    </div>
    <div id="googleMap" style="width:100%;height:400px;"></div>
    <input type="hidden" id="lat" value="">
    <input type="hidden" id="lng" value="">
    <input type="hidden" id="acc" value="">
    <div class="description">
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.</p>
        <p>Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. </p>
    </div>


    <div id="nxtPrv" >
        <div id="prv" > Previous </div>
        <div id="nxt" > Next </div>
    </div>

    <div id="storesList">
        Store loads here ...
    </div>


</div>
</body>
<script>
    /*
    Search Function
     */
    $("#searchButton").click(function(){
        var input = $( "#searchBox" ).val();
        console.log (input);
        var geocoder = new google.maps.Geocoder();

        geocoder.geocode( { 'address': input}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                var lat     = results[0].geometry.location.lat(); //51.823872;
                var lng     = results[0].geometry.location.lng(); //-3.019166;
                var radius  = 200;
                var start   = 0;
                var rows    = 50;
                var zoom    = 10;

                $('#lookingCoordinates‎').hide();
                getMapMarkers(lat, lng,  radius, start, rows, zoom);
            }
        });
        return false;
    });
</script>

<script>

    var mar=[];
    var map;

    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
        console.log('Looking for your Lat && lng, Please wait.');
        navigator.geolocation.getCurrentPosition(fetchPlacesMobile);
        $('#lookingCoordinates‎').show();
    }
    else{
        fetchPlacesDesktop();
//        console.log('Looking for your Lat && lng, Please wait.');
//        navigator.geolocation.getCurrentPosition(fetchPlacesMobile);
//        $('#lookingCoordinates‎').show();
    }
/*
 function GetLocation(location) {
 document.getElementById("lat").value = location.coords.latitude;
 document.getElementById("lng").value = location.coords.longitude;
 document.getElementById("acc").value = location.coords.accuracy ;
 console.log(document.getElementById('lat').value + ' ' + document.getElementById('lng').value);
 }
 */
    function  loadStores(lat, lng, start) {
        console.log("I am in fetchPlacesMobile");
        var lat     = lat; //51.823872;
        var lng     = lng; //-3.019166;
        var radius  = 200;
        var start   = start;
        var rows    = 5;
        var zoom    = 8;

        $('#lookingCoordinates‎').hide();
        getMapMarkers(lat, lng,  radius, start, rows, zoom);
    };

    function  fetchPlacesMobile(location) {
        console.log("I am in fetchPlacesMobile");
        var lat     = location.coords.latitude; //51.823872;
        var lng     = location.coords.longitude; //-3.019166;
        var radius  = 200;
        var start   = 0;
        var rows    = 5;
        var zoom    = 14;

        $('#lookingCoordinates‎').hide();
        getMapMarkers(lat, lng,  radius, start, rows, zoom);
    };

    function  fetchPlacesDesktop() {
        console.log("I am in fetchPlacesDesktop");
        var lat     = 53.089362;
        var lng     = -4.852386;
        var radius  = 400;
        var start   = 0;
        var rows    = 0;
        var zoom    = 6;
        $('#lookingCoordinates‎').hide();
        getMapMarkers(lat, lng,  radius, start, rows, zoom);
    };

    function setRadius(radiusInput){
        if (radiusInput == 10)  return 16;
        if (radiusInput == 20)  return 14;
        if (radiusInput == 30)  return 10;
        if (radiusInput == 50)  return 9;
        if (radiusInput == 100) return 9;
        return 6;
    }

//    function getMapMarkers(lat=51.5072, lng=0.1275, radius=400, start=0, rows=100, zoom=12) {
    function getMapMarkers(lat, lng, radius, start, rows, zoom) {
        console.log("lat :: " + lat + " >> lng :: " + lng + ' >> ' );
        mar = [];
        var mapOptions = {
            center: new google.maps.LatLng(lat, lng),
            zoom: zoom,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        map = new google.maps.Map(document.getElementById("googleMap"), mapOptions);
        console.log("map init Succeeded");

        var dataUrl =  "<?=$this->getUrl('storelocator/clickncollect/stores', array())?>" ;
        var form_data = {
            s:  <?= Mage::app()->getStore()->getStoreId();?>,
            lat: lat,
            lng: lng,
            w: radius,
            m: true,
            start: start,
            rows: rows,
            ajax: '1'
        };
        console.log("dataUrl :: " + dataUrl );
        var storeList = '';
        jQuery.ajax({
            url : dataUrl,
            dataType : 'json',
            type: 'GET',
            data: form_data,
            success : function(response) {
                console.log("Success StoreData :: " + response.status );
                if (response.status == 'OK') {
                    var places = response.places;
                    console.log("Total records :: " + response.records);
                    // loop through places and add markers
                    var s =0;
//                    var bound = new google.maps.LatLngBounds();
                    for (s in places) {
                        var p = places[s];
//                        bound.extend( new google.maps.LatLng(p.lat, p.lng) );
                        var infoData = getInfoData(p);
                        genMarkers(p.lat, p.lng, infoData, p.map_zoom_list_page);
                        storeList += genStoreList(p, s, lat, lng);
                    }
                    $('#storesList').html(storeList).show();
                    var firstElement =  parseInt(start) -  5;   // parseInt(response.records);
                    var lastElement =  parseInt(start) + 5;     // parseInt(response.records);
//                    var tempLat = tempLng = 2;
//                    map.setCenter(new google.maps.LatLng(bound.getCenter()));
                    $('#prv').html('<a href="#" onclick="loadStores(\'' + lat + '\' , \'' + lng + '\',  \'' +  firstElement + '\');" > Previous </a> ');
                    $('#nxt').html('<a href="#" onclick="loadStores(\'' + lat + '\' , \'' + lng + '\',  \'' + lastElement + '\');" > Next </a> ');
                }
            }
        })
    };

    function genMarkers(lat, lng, infoData, zoom){
        var mark =  new google.maps.Marker({ map: map, position:  new google.maps.LatLng( lat, lng) });

        mark['infowindow'] =  new google.maps.InfoWindow({ content: infoData });
        mark['zoom'] =   parseInt(zoom);

        google.maps.event.addListener(mark, 'click', function() {
            closeInfoWindows();
            map.setZoom(mark['zoom']);
            mark['infowindow'].open(map, mark);
        });
        mar.push(mark);
    }


    function gotoMarker(myPoint){
        closeInfoWindows();
        window.scrollTo(0, 110);  // Scroll to Map
        var zoom =mar[myPoint]['zoom'];
        map.setZoom(zoom);  // Set Map Zoom
        console.log(myPoint + ' >> ' +  mar[myPoint].position.lat() + ' >> ' + mar[myPoint].position.lng() + ' zoom>> ' + zoom);
        map.setCenter(new google.maps.LatLng(mar[myPoint].position.lat(), mar[myPoint].position.lng()));
        mar[myPoint]['infowindow'].open(map, mar[myPoint]);
    }

    function genStoreList(p, s, lat, lng){
        var distance = getDistanceFromLatLon(lat, lng, p.lat, p.lng);
        distance = distance.toFixed(2);
        var storeList='';
        if(distance != 'NaN' ){  // TODO :: This is not correct way to filter, need to find a better way to filter empty array
            var geoName = p.unique_name;
            storeList += '<b onclick="loadAddress( \'' + p.unique_name  + '\');" >' + p.branch_name + '</b> (' + distance +  ' Mile) <br />';
            storeList += p.address1 + ', ' + p.city + ', ' + p.postcode + '<br />';
//            storeList += 'Lat Lng >> ' + p.lat + ', ' + p.lng +  '<br />';
            storeList += '<div class="viewOnMap" onClick="gotoMarker( \'' + s + '\');"  > View On Map </div>';
            storeList += "<div class='goToStore'  > <a href='/"+ p.unique_name +"\'> Go To Store </a> </div>";
            storeList += '<hr>';
//            console.log(p.unique_name);
        }
        return storeList;
    };


    /// Lazy Functions ....  //////////////////
    function getInfoData(p){
        var name = p.unique_name;
        var branch_name = p.branch_name;
        var phone                          = p.phone;
        var address                        = p.address1 + ', <br /> ' + p.city + '<br /> ' + p. postcode;
        var url                            = '/'+name;
        var viewDetails                    = '<a href="'+ url + '"> View Details </a>';

        var openingHours = "<div class=\'openingHoursTitle\'> Opening Hours </div>";

        openingHours += formateOpeningHopurs(p);


        var details = "<h1>"+ branch_name +"</h1>";
        details += "<p>" + address + "</p>";
        details += "<p>" + phone + "</p>";
        details += "<p>" + viewDetails + "</p>";

        var infoWindow = "<div class=\'infoWindow\'> ";
        infoWindow += "<div class=\'details\'>" +  details + "  </div>";
        infoWindow += "<div class=\'openingHours\'> " + openingHours + "</div>";
        infoWindow += "</div>";
        return infoWindow;
    }

    function formateOpeningHopurs(p){
        var oHours = new Object();
        oHours[0] = {"day" : "Monday",      "Open" : p.mon_open,    "Close" : p.mon_close};
        oHours[1] = {"day" : "Tuesday",     "Open" : p.tues_open,   "Close" : p.tues_close};
        oHours[2] = {"day" : "Wednusday",   "Open" : p.wednes_open, "Close" : p.wednes_close};
        oHours[3] = {"day" : "Thursday",    "Open" : p.thurs_open,  "Close" : p.thurs_close};
        oHours[4] = {"day" : "Friday",      "Open" : p.fri_open,    "Close" : p.fri_close};
        oHours[5] = {"day" : "Saturday",    "Open" : p.satur_open,  "Close" : p.satur_open};
        oHours[6] = {"day" : "Sunday",      "Open" : p.sun_open,    "Close" : p.sun_close};

        var oHoursData = '<table style="width:200px">';
        for (s in oHours) {
            oHoursData += '<tr>';
            oHoursData += '<td>'+ oHours[s].day +'</td>';
            oHoursData += '<td>'+ minToHour(oHours[s].Open) +'</td>';
            oHoursData += '<td>'+ minToHour(oHours[s].Close) +'</td>';
            oHoursData += '</tr>';
        }
        oHoursData += '</table>';
        return oHoursData;
    }
    function closeInfoWindows(){
        for (var i=0; i<mar.length; i++) {
            mar[i]['infowindow'].close();
        }  // Close all infoWindows
    }

    function minToHour(min){
        var mn = min%60;
        var hour   = (min - mn )/60;
        var ampm   = (hour < 12 ) ? 'AM'      : 'PM';
        hour   = (hour < 12 ) ? hour     : hour-12;
        hour   = (hour < 10 ) ? '0'+hour : hour;
        mn     = (mn < 10 )   ? '0'+mn   : mn;
        return hour+':'+mn+ampm;
    }



    function getDistanceFromLatLon(lat1,lon1,lat2,lon2) {
        var R = 3959; // Radius of the earth in mile
        var dLat = deg2rad(lat2-lat1);  // deg2rad below
        var dLon = deg2rad(lon2-lon1);
        var a =
                Math.sin(dLat/2) * Math.sin(dLat/2) +
                    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) *
                        Math.sin(dLon/2) * Math.sin(dLon/2)
            ;
        var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
        var d = R * c; // Distance in Mile
//        console.log("From  " + lat1 + lon1 + ' To ' + lat2 + lon2 +  " Distance> " + d );
        return d;
    };

    function deg2rad(deg) {
        return deg * (Math.PI/180)
    };

//    google.maps.event.addDomListener(window, 'load', fetchPlacesDesktop);
</script>
