
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="/js/storelocator/jquery.bpopup.min.js"></script>
<style>
    #element_to_pop_up {
        background-color:#fff;
        border-radius:15px;
        color:#000;
        display:none;
        padding:20px;
        min-width:900px;
        min-height: 90%;
    }
    .b-close{
        cursor:pointer;
        position:absolute;
        right:10px;
        top:5px;
    }
    #map-content{
        width:980px;
        height:500px;
    }
    .CollectFromHere{
        background: #0dffe6;
    }
</style>


<!-- Button that triggers the popup -->
<button id="my-button">POP IT UP</button>
<div id="content">  Address to show here </div>
<!-- Element to pop up -->
<div id="element_to_pop_up">
    <a class="b-close">close<a/>
        <div id="searchInput">
            <input type="text" name="address"  id="centerInput"  placeholder="Enter Town Or Postcode">
            <select name="options" id="radiusInput" >
                <option value="10">10mi</option>
                <option value="20">20mi</option>
                <option value="30">30mi</option>
                <option value="50">50mi</option>
                <option value="100">100mi</option>
            </select>
            <input type="submit" class="searchButton" value="SEARCH" onclick="fetchPlaces();">
            <button id="my-button">Reset</button>
        </div>


        <div id="map-content">
            <img src="https://www.ryman.co.uk/media/wysiwyg/ryman/misc/ryman_store_photo.jpg" width="100%"/>
        </div>
</div>
<img src="https://www.ryman.co.uk/media/wysiwyg/ryman/misc/ryman_store_photo.jpg" width="100%"/>

<script>
    var markers = [];
    var lat = '';
    var lng = '';

    var infowindow =  new google.maps.InfoWindow({
        content: ''
    });
    function myFunction() {
        console.log("I am in myFunction");
        fetchPlaces();
        return false;
    }
    function  fetchPlaces() {
        console.log("I am in fetchPlaces");
        var centerInput =  jQuery("#centerInput").val();
        var radiusInput =  jQuery("#radiusInput").val();



        console.log("centerInput :: " + centerInput + " >> radiusInput :: " + radiusInput);
        jQuery.ajax({
            url : "http://maps.googleapis.com/maps/api/geocode/json?address=" + centerInput + "&sensor=false",
            dataType : 'json',
            success : function(response) {
                console.log("Success LatLng : " + response.status );
                if (response.status == 'OK') {
                    lat = response.results[0].geometry.viewport.northeast.lat;
                    lng = response.results[0].geometry.viewport.northeast.lng;
                    console.log("lat :: " + lat + " >> lng :: " + lng);
                    getMarkers(lat, lng, radiusInput );
                }
            }
        })
    };

    function getMarkers(lat, lng, radiusInput ) {
        console.log("lat :: " + lat + " >> lng :: " + lng);
        var mapOptions = {
            center: new google.maps.LatLng(lat, lng),
            zoom: 8,
            mapTypeId: 'roadmap'
        };
        console.log("MapOption init Succeeded");
        var map = new google.maps.Map(document.getElementById("map-content"), mapOptions);
        console.log("map init Succeeded");

        var dataUrl = '/api/data.php?s=1&w='+radiusInput+'&lat=' + lat +'&lng='+ lng + '&lb=0&le=200';
        console.log("dataUrl :: " + dataUrl );
        jQuery.ajax({
            url : dataUrl,
            dataType : 'json',
            success : function(response) {
                console.log("Success StoreData :: " + response.status );
                if (response.status == 'OK') {
                    places = response.places;

                    console.log("Total records :: " + response.records);
                    // loop through places and add markers
                    for (p in places) {
                        console.log("Place  " +  places[p].name + ' geo0 :: ' + places[p].geo[0] );
                        //create gmap latlng obj
                        tmpLatLng = new google.maps.LatLng( places[p].geo[0], places[p].geo[1]);
                        // make and place map maker.
                        var marker = new google.maps.Marker({
                            map: map,
                            position: tmpLatLng
                        });
                        bindInfoWindow(marker, map, infowindow, '<div   onclick="loadAddress( \'' + places[p].name  + '\');"> Collect From ' + places[p].name  + '</div>');
                    }
                }
            }
        })
    };

    // binds a map marker and infoWindow together on click
    var bindInfoWindow = function(marker, map, infowindow, html) {
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.setContent(html);
            infowindow.open(map, marker);
        });
    };

    function loadAddress(name){
        console.log("popUpclosed; I'm in loadAddress");
        $( "#element_to_pop_up" ).bPopup().close();
        $('#content').html('This is the new address ... ' + name );
    };

</script>


<script>
    // Semicolon (;) to ensure closing of earlier scripting
    // Encapsulation
    // $ is assigned to jQuery ;
    ; (function($) {
        // DOM Ready
        $(function() {

            // Binding a click event
            // From jQuery v.1.7.0 use .on() instead of .bind()
            $('#my-button').bind('click', function(e) {

                // Prevents the default action to be triggered.
                e.preventDefault();

                // Triggering bPopup when click event is fired
                $('#element_to_pop_up').bPopup();

            });

        });

    })(jQuery);
</script>


